function DB=fn_initDB()
% initializing DB structure
% 10/31/2010
% coded by Yoshi Yamamoto (Stanford University)
% yama4423@stanford.edu

DB = struct('M',{},'hdist',{},'vs30',{}, ...
    'minorElx',{}, 'minorSlx',{}, 'minorVlx',{}, 'minorEly',{}, 'minorSly',{}, 'minorVly',{},'minorRlxly',{}, ...
    'majorElx',{}, 'majorSlx',{}, 'majorVlx',{}, 'majorEly',{}, 'majorSly',{}, 'majorVly',{},'majorRlxly',{}, ...
    'totalEnergy',{}, 'majorEa',{}, 'minorRnd',{} ...
    );
